---
title: "Penguins Data ETL (DuckDB database)"
execute:
    echo: true
    output: true
    message: false
    warning: false
format:
    html:
        code-fold: true
---

## Load penguins data into DuckDB local file store

### Python Version

Note: It seems quarto is using reticulate. I do not want to check how quarto is handling uv/venv so the next cell will not be evaluated. See also the note in the README.md, I just used the R version


```{python}
#| eval: FALSE
import duckdb
from palmerpenguins import penguins

con = duckdb.connect('data/my-db.duckdb')
df = penguins.load_penguins()
df.head()
# Assign operations to variables just to keep from printing results on website
exe_result = con.execute('CREATE OR REPLACE TABLE penguins AS SELECT * FROM df')
cls_result = con.close()
```

### Same thing in `R`:

```{r}
#| label: Write data to duckdb file

# penguins data is in R 4.5 but you could be in older version 
setup_penguin_db <- function(){
    if (!dir.exists("data")) dir.create("data")
    message("Creating data/ directory")
    message("DBI and duckdb are used")
    on.exit(DBI::dbDisconnect(con), add = TRUE)
    con <- DBI::dbConnect(duckdb::duckdb(), 
                          dbdir = "data/my-db.duckdb", 
                          shutdown = TRUE)
    DBI::dbWriteTable(con, 
                     "penguins", 
                     palmerpenguins::penguins, 
                     overwrite = TRUE)
    message("Writing data/my-db.duckdb")
    # pissed he just write parquet 
    DBI::dbExecute(con, "COPY
                            (select * from penguins)
                        TO 'data/penguins.parquet'
                        (FORMAT parquet);")
    message("Writing data/penguins.parquet")

} 

setup_penguin_db()
```


Is the process correctly setup: `grepl("my-db.duckdb", list.files("data/"))

## Write data to JSON with DuckDB

```{r}
#| label: Write data to json file
# duckdb::dbSendQuery(con, "INSTALL json;")
# duckdb::dbSendQuery(con, "LOAD json;")
# duckdb::dbSendQuery(con, "COPY (SELECT * FROM penguins) TO './data/penguins.json' (ARRAY true);")
```
