---
title: "Penguins Exploratory Data Analysis"
execute:
    echo: true
    output: true
    message: false
    warning: false
format:
    html:
        code-fold: true
---

## Penguin Size and Mass by Sex and Species


```{r}
#| label: Import packages and penguins data
if (!require(dplyr) || !require(ggplot2) || !require(palmerpenguins)) {
    install.packages(c("dplyr", "ggplot2", "palmerpenguins"))
    library(dplyr)
    library(ggplot2)
    library(palmerpenguins)
}

```

```{r}
#| label: Get penguins data from DuckDB database

# df <- palmerpenguins::penguins

library(duckdb)

con <- DBI::dbConnect(
  duckdb::duckdb(),
  dbdir = "data/my-db.duckdb"
  )
df <- dplyr::tbl(con, "penguins")
# DBI::dbDisconnect(con)
```


```{r}
#| label: Summarize penguin data
# df |>
#   group_by(species, sex) |>
#   summarise(
#     across(
#       where(is.numeric),
#       \(x) mean(x, na.rm = TRUE)
#     )
#   ) |>
#   knitr::kable()

## Passing a predicate to tidy no longer works when using a duckdb table...
## Error in summarise(group_by(df, species, sex), across(where(is.numeric), : ℹ In argument: `across(where(is.numeric), function(x) mean(x, na.rm = TRUE))`
## Caused by error in `across()`:
## ! This tidyselect interface doesn't support predicates.
```

## Penguin Size vs Mass by Species


```{r}
#| label: Plot penguins data
df |>
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() +
  geom_smooth(method = "lm")
```

Finally, close the duckdb connection *after* all operation on the data.frame are complete

```{r}
#| label: Close the duckdb connection

DBI::dbDisconnect(con)
```
