project:
  type: website

website:
  title: "do4ds_project"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - 00_data.qmd
      - 01_eda.qmd
      - 02_model.qmd
