---
title: "Penguins Exploratory Data Analysis"
execute:
    echo: true
    output: true
    message: false
    warning: false
format:
    html:
        code-fold: true
---

## Penguin Size and Mass by Sex and Species


```{r}
#| label: Import packages and penguins data
if (!require(dplyr) || !require(ggplot2) || !require(palmerpenguins)) {
    install.packages(c("dplyr", "ggplot2", "palmerpenguins"))
    library(dplyr)
    library(ggplot2)
    library(palmerpenguins)
}

df <- palmerpenguins::penguins

# Get penguins data from DuckDB database
con <- DBI::dbConnect(
  duckdb::duckdb(),
  dbdir = "my-db.duckdb"
  )
df <- dplyr::tbl(con, "penguins")
```

```{r}
#| Get penguins data from DuckDB database

#df <- palmerpenguins::penguins

con <- DBI::dbConnect(
  duckdb::duckdb(),
  dbdir = "data/my-db.duckdb"
  )
df <- dplyr::tbl(con, "penguins")
DBI::dbDisconnect(con)
```


```{r}
#| label: Summarize penguin data
df |>
  group_by(species, sex) |>
  summarise(
    across(
      where(is.numeric),
      \(x) mean(x, na.rm = TRUE)
      )
    ) |>
  knitr::kable()
```

## Penguin Size vs Mass by Species


```{r}
#| label: Plot penguins data
df |>
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() +
  geom_smooth(method = "lm")
```

